import { X } from 'lucide-react'

// ── Legal documents (Terms of Service + Privacy Policy) ──────────────────────
// Plain-content drafts modeled on Robinhood's structure, adapted for Emouva: a solo-
// developer technology platform (not yet an entity) offering AI research + an optional
// AI "Partner" that trades a user's connected brokerage under their mandate. The risk
// + liability sections (Terms §5, §6) are the load-bearing ones.
// NOTE: not attorney-drafted — have counsel review before relying on it commercially.

const LAST_UPDATED = 'July 8, 2026'
const CONTACT = 'support@emouva.com'

type Section = { h: string; p: string[] }

const TERMS: Section[] = [
  { h: '', p: [
    `Last updated: ${LAST_UPDATED}`,
    'IMPORTANT — PLEASE READ CAREFULLY. Emouva can place REAL trades in a brokerage account you connect. Trading securities can result in the COMPLETE AND TOTAL LOSS of the money in that account. Emouva and its developer are NOT responsible for any losses resulting from trading. Do not enable live trading with money you cannot afford to lose. See Sections 5 and 6.',
  ] },
  { h: '1. Agreement to These Terms', p: [
    'These Terms of Service ("Terms") govern your access to and use of Emouva (the "Service"), a software platform operated by its sole developer and owner (the "Developer"). In these Terms, "Emouva," "we," "us," and "our" refer to the Service and the Developer. "You" and "your" refer to you, the user.',
    'By creating an account, signing in, or otherwise using the Service, you agree to be bound by these Terms and by our Privacy Policy. If you do not agree, do not use the Service.',
  ] },
  { h: '2. What Emouva Is — and Is Not', p: [
    'Emouva is a technology platform that provides (a) AI-generated investment research, scores, and analytics, and (b) an optional AI "Partner" that can place equity orders in a brokerage account you connect, strictly within limits (a "mandate") you configure.',
    'Emouva is NOT a broker-dealer, NOT a registered investment adviser, NOT a bank, and NOT a fiduciary. Emouva does not hold, custody, or have withdrawal access to your money or securities. All orders are routed to and executed by your own connected brokerage (for example, Robinhood), whose separate agreements govern execution, settlement, and custody. Emouva is a technology tool only; nothing it provides is personalized investment, legal, tax, or financial advice.',
  ] },
  { h: '3. Eligibility', p: [
    'You must be at least 18 years old, a resident of a jurisdiction where the Service is available, and legally able to enter into a binding contract. You must own, and be authorized to use, any brokerage account you connect. You are responsible for complying with all laws applicable to your use of the Service and your trading.',
  ] },
  { h: '4. Informational Only — No Advice', p: [
    'All research, scores, theses, fair-value estimates, and other output are provided for informational and educational purposes only, are generated by automated systems and third-party data, and may be inaccurate, incomplete, or out of date. They are not a recommendation, solicitation, or offer to buy or sell any security, and are not tailored to your financial situation. You are solely responsible for evaluating the merits and risks of any investment decision.',
  ] },
  { h: '5. Agentic Trading — Substantial Risk and Your Sole Responsibility', p: [
    'Paper trading uses simulated money only. If you enable live (agentic) trading, the AI Partner will place REAL orders using REAL money in your connected brokerage account, automatically and without prior review of each order, within the mandate and limits you configure.',
    'Trading securities involves substantial risk, including the risk of COMPLETE AND TOTAL LOSS of the capital in the connected account. Markets are volatile and unpredictable, and losses can occur rapidly.',
    'The AI Partner is experimental automated software. It can make mistakes; misinterpret information; act on inaccurate, delayed, or incomplete third-party data; malfunction; behave in unexpected ways; and execute trades you would not have chosen. Automated systems can compound errors quickly and may place trades at unfavorable prices or times.',
    'Past performance and simulated (paper) performance are NOT indicative of and do not guarantee future results.',
    'You are solely responsible for configuring your mandate and limits, for monitoring your account, for using the pause and halt controls, and for ALL trades, activity, and outcomes in your account. By enabling live trading, you knowingly and voluntarily accept all of these risks and assume full and sole responsibility for any and all resulting losses.',
  ] },
  { h: '6. No Liability for Trading or Other Losses', p: [
    'To the maximum extent permitted by law, Emouva, the Developer, and their owners, operators, contractors, agents, and affiliates (collectively, the "Emouva Parties") shall NOT be liable for any loss of capital, trading loss, lost profits, lost opportunity, or any direct, indirect, incidental, special, consequential, exemplary, or punitive damages arising out of or relating to the Service, the AI Partner, any order placed or not placed, any data or output, or your use of or inability to use the Service — even if advised of the possibility of such damages.',
    'Without limiting the foregoing, the Emouva Parties are NOT responsible for any losses resulting from trading, including losses caused by the AI Partner’s decisions, actions, errors, delays, or failures. You agree that your sole and exclusive remedy for any dissatisfaction with the Service is to stop using it.',
    'Some jurisdictions do not allow certain limitations of liability; where that applies to you, the limitations apply to the greatest extent permitted by law, and in no event shall the Emouva Parties’ total aggregate liability exceed the greater of the subscription fees you paid to Emouva in the three (3) months before the claim or US$50.',
  ] },
  { h: '7. Disclaimer of Warranties', p: [
    'The Service is provided "AS IS" and "AS AVAILABLE," without warranties of any kind, express or implied, including any warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, reliability, or availability. We do not warrant that the Service will be uninterrupted, error-free, or secure, that any output is accurate, or that use of the Service will be profitable or achieve any particular result. Market and financial data are provided by third parties and may be delayed, inaccurate, or unavailable.',
  ] },
  { h: '8. Indemnification', p: [
    'You agree to indemnify, defend, and hold harmless the Emouva Parties from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or related to your use of the Service, your trades and account activity, your violation of these Terms, or your violation of any law or third-party right.',
  ] },
  { h: '9. Brokerage Connection and Authorization', p: [
    'When you connect a brokerage, you authorize Emouva to access your account through secure authorization (such as OAuth) to read account and market data and, only if you enable live trading, to place orders within your mandate. You may revoke this authorization at any time through the Service or your brokerage. Emouva never receives your brokerage password and never has custody of, or the ability to withdraw, your funds or securities.',
  ] },
  { h: '10. Your Account and Security', p: [
    'You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account. Notify us promptly of any unauthorized use. We are not liable for losses arising from your failure to safeguard your credentials.',
  ] },
  { h: '11. Free and Open-Source Service', p: [
    'Emouva is free to use and its source code is available under the MIT license. There are no subscriptions or platform fees. AI features run on your own API key with your AI provider, and any usage fees for that key, for market-data subscriptions you add, or for your brokerage are between you and those providers.',
  ] },
  { h: '12. Acceptable Use', p: [
    'You agree not to misuse the Service, including by: using it for any unlawful purpose; attempting to circumvent trading limits, safety controls, or security; reverse engineering, scraping, or overloading the Service; or interfering with other users or the operation of the Service.',
  ] },
  { h: '13. Intellectual Property', p: [
    'The Service, including its software, models, design, and content, is owned by the Developer and protected by intellectual-property laws. You receive a limited, non-exclusive, non-transferable, revocable license to use the Service for its intended purpose. All rights not expressly granted are reserved.',
  ] },
  { h: '14. Changes to the Service or Terms', p: [
    'We may modify, suspend, or discontinue any part of the Service at any time. We may update these Terms; material changes will be indicated by updating the "Last updated" date and, where appropriate, additional notice. Your continued use after changes take effect constitutes acceptance.',
  ] },
  { h: '15. Termination', p: [
    'You may stop using the Service at any time. We may suspend or terminate your access, with or without notice, for any reason, including breach of these Terms. Sections that by their nature should survive termination (including Sections 5–8) will survive.',
  ] },
  { h: '16. Governing Law and Disputes', p: [
    'These Terms are governed by the laws of the State in which the Developer resides and applicable U.S. federal law, without regard to conflict-of-law rules. To the extent permitted by law, you agree that any dispute will be resolved on an individual basis and not as part of any class or representative action.',
  ] },
  { h: '17. Contact', p: [
    `Questions about these Terms can be sent to ${CONTACT}.`,
  ] },
]

const PRIVACY: Section[] = [
  { h: '', p: [
    `Last updated: ${LAST_UPDATED}`,
    'This Privacy Policy explains how Emouva (the "Service"), operated by its sole developer (the "Developer," "we," "us"), collects, uses, and shares your information. By using the Service you agree to this Policy.',
  ] },
  { h: '1. Information We Collect', p: [
    'Account information: your username, email address, display name, and a securely hashed password.',
    'Brokerage and portfolio data: if you connect a brokerage, we access your account balances, buying power, positions, orders, and trade history through secure authorization to power the Service. We do not receive your brokerage password.',
    'Usage data: your watchlist, mandate and settings, agent activity and ledger, research requests, and application logs.',
    'Technical data: device, browser, and basic diagnostic information.',
  ] },
  { h: '2. How We Use Your Information', p: [
    'To provide and operate the Service; to generate the AI research and, where you enable it, the agentic trading you request; to communicate with you; to maintain security and prevent fraud; to improve the Service; and to comply with legal obligations.',
  ] },
  { h: '3. How We Share Your Information', p: [
    'We do NOT sell your personal information. We share data only as needed to run the Service, including with: our AI provider (Anthropic) to generate research and trade decisions; market-data providers (such as Financial Modeling Prep and Finnhub — generally ticker-level, not personal); your connected brokerage (such as Robinhood) to read data and place orders you authorize; and hosting/infrastructure providers (such as Google Cloud). We may also share information to comply with law or in connection with a business transfer.',
  ] },
  { h: '4. AI Processing', p: [
    'To generate research and trading decisions, relevant information — such as your holdings, the tickers you view, and your mandate settings — is transmitted to our AI provider for processing and is handled subject to that provider’s terms. Do not enter information you do not want processed for these purposes.',
  ] },
  { h: '5. Data Security', p: [
    'We use industry-standard measures, including encryption in transit and encryption at rest for sensitive credentials and brokerage tokens. However, no method of transmission or storage is completely secure, and we cannot guarantee absolute security.',
  ] },
  { h: '6. Data Retention', p: [
    'We retain your information for as long as your account is active and as needed to provide the Service, comply with legal obligations, resolve disputes, and enforce agreements. You may request deletion of your account and associated data (subject to limited legal/operational exceptions).',
  ] },
  { h: '7. Your Choices and Rights', p: [
    'You can access and update your account information, disconnect your brokerage at any time, cancel your subscription, and request deletion of your account. Depending on your location, you may have additional rights over your personal data. To exercise these, contact us.',
  ] },
  { h: '8. Cookies and Local Storage', p: [
    'We use browser local storage and authentication tokens to keep you signed in and remember preferences, and minimal cookies necessary to operate the Service.',
  ] },
  { h: '9. Children’s Privacy', p: [
    'The Service is not directed to individuals under 18, and we do not knowingly collect personal information from minors. If you believe a minor has provided us information, contact us and we will delete it.',
  ] },
  { h: '10. Third-Party Services', p: [
    'Your brokerage, payment processor, and other third parties have their own privacy policies that govern their handling of your information. This Policy covers only Emouva.',
  ] },
  { h: '11. Changes to This Policy', p: [
    'We may update this Policy from time to time. Material changes will be indicated by updating the "Last updated" date and, where appropriate, additional notice.',
  ] },
  { h: '12. Contact', p: [
    `Questions about this Policy can be sent to ${CONTACT}.`,
  ] },
]

const DOCS: Record<'terms' | 'privacy', { title: string; sections: Section[] }> = {
  terms: { title: 'Terms of Service', sections: TERMS },
  privacy: { title: 'Privacy Policy', sections: PRIVACY },
}

export type LegalDoc = 'terms' | 'privacy'

export default function LegalModal({ doc, onClose }: { doc: LegalDoc | null; onClose: () => void }) {
  if (!doc) return null
  const { title, sections } = DOCS[doc]
  return (
    <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4" onClick={onClose}>
      <div
        className="w-full max-w-2xl max-h-[85vh] flex flex-col rounded-[12px] bg-surface-2 border border-[rgba(180,220,190,0.14)] shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-6 py-4 border-b border-[rgba(180,220,190,0.10)] flex-none">
          <h2 className="text-[16px] font-serif font-medium text-text-primary tracking-tight">{title}</h2>
          <button onClick={onClose} aria-label="Close" className="p-1.5 rounded-md text-text-tertiary hover:text-text-primary hover:bg-[rgba(180,220,190,0.08)] transition-colors">
            <X className="w-4.5 h-4.5" strokeWidth={1.75} />
          </button>
        </div>
        <div className="overflow-y-auto px-6 py-5 space-y-5">
          {sections.map((s, i) => (
            <div key={i}>
              {s.h && <h3 className="text-[13px] font-semibold text-text-primary mb-2">{s.h}</h3>}
              {s.p.map((para, j) => (
                <p key={j} className={`text-[12.5px] leading-relaxed text-text-secondary ${j > 0 ? 'mt-2' : ''} ${!s.h && j === 1 ? 'text-warning/90 font-medium' : ''}`}>
                  {para}
                </p>
              ))}
            </div>
          ))}
          <p className="text-[11px] text-text-tertiary pt-2 border-t border-[rgba(180,220,190,0.08)]">
            By using Emouva you acknowledge that you have read and agree to this document.
          </p>
        </div>
      </div>
    </div>
  )
}
